global:
  wizApiToken:
    secret:
      create: false # We create it manually
      name: "wiz-api-token"

wiz-kubernetes-connector:
  enabled: true
  autoCreateConnector:
    connectorName: "my-tests-cluster"
  broker:
    enabled: true

wiz-sensor:
  enabled: true
  imagePullSecret:
    create: false # We create it manually
    name: "sensor-image-pull"
  daemonset:
    # resource values for the wiz sensor
    resources:
      limits:
        cpu: "300m"
        memory: "300Mi"
      requests:
        cpu: "10m"
        memory: "50Mi"

wiz-admission-controller:
  enabled: true
